const colors = [
  { id: 'Amarelo', name: 'Amarelo', hex: '#ffff00' },
  { id: 'Azul', name: 'Azul', hex: '#0000ff' },
  { id: 'Azul marinho', name: 'Azul marinho', hex: '#120a8f' },
  { id: 'Bege', name: 'Bege', hex: '#f5f5dc' },
  { id: 'Bordô', name: 'Bordô', hex: '#800000' },
  { id: 'Branco', name: 'Branco', hex: '#ffffff' },
  { id: 'Bronze', name: 'Bronze', hex: '#cd7fc2' },
  { id: 'Café', name: 'Café', hex: '#a38068' },
  { id: 'Caramelo', name: 'Caramelo', hex: '#8b5724' },
  { id: 'Castanho', name: 'Castanho', hex: '#422600' },
  { id: 'Cinza', name: 'Cinza', hex: '#808080' },
  { id: 'Coral', name: 'Coral', hex: '#ff7f50' },
  { id: 'Dourado', name: 'Dourado', hex: '#ffd700' },
  { id: 'Floral', name: 'Floral', hex: '#fffaf0' },
  { id: 'Grafite', name: 'Grafite', hex: '#474a51' },
  { id: 'Incolor', name: 'Incolor', hex: 'rgba(0,0,0,0)' },
  { id: 'Laranja', name: 'Laranja', hex: '#ffa500' },
  { id: 'Listra', name: 'Listra', hex: '#fff' },
  { id: 'Marrom', name: 'Marrom', hex: '#964b00' },
  { id: 'Multicolorido', name: 'Multicolorido', hex: '#fff' },
  { id: 'Nude', name: 'Nude', hex: '#ebc8b2' },
  { id: 'Off-white', name: 'Off-white', hex: '#fbfbf8' },
  { id: 'Prata', name: 'Prata', hex: '#d5d5d5' },
  { id: 'Preto', name: 'Preto', hex: '#000000' },
  { id: 'Rosa', name: 'Rosa', hex: '#ff007f' },
  { id: 'Roxo', name: 'Roxo', hex: '#993399' },
  { id: 'Único', name: 'Único', hex: '#fff' },
  { id: 'Verde', name: 'Verde', hex: '#008000' },
  { id: 'Verde oliva', name: 'Verde Oliva', hex: '#78866b' },
  { id: 'Vermelho', name: 'Vermelho', hex: '#ff0000' },
  { id: 'Vinho', name: 'Vinho', hex: '#7d2c40' },
  { id: 'Xadrez', name: 'Xadrez', hex: 'rgba(0,0,0,0)' },
  { id: 'Diversas', name: 'Diversas', hex: 'rgba(0,0,0,0)' },
];

export default colors;
