const sizes = [
  { id: 'PP', name: 'PP', checked: false },
  { id: 'P', name: 'P', checked: false },
  { id: 'M', name: 'M', checked: false },
  { id: 'G', name: 'G', checked: false },
  { id: 'GG', name: 'GG', checked: false },
  { id: 'XG', name: 'XG', checked: false },
  { id: '1', name: '1', checked: false },
  { id: '2', name: '2', checked: false },
  { id: '2 - M', name: '2 - M', checked: false },
  { id: '2 - P', name: '2 - P', checked: false },
  { id: '3', name: '3', checked: false },
  { id: '3 - M', name: '3 - M', checked: false },
  { id: '4 - G', name: '4 - G', checked: false },
  { id: '12', name: '12', checked: false },
  { id: '14', name: '14', checked: false },
  { id: '16', name: '16', checked: false },
  { id: '18', name: '18', checked: false },
  { id: '32', name: '32', checked: false },
  { id: '34', name: '34', checked: false },
  { id: '36', name: '36', checked: false },
  { id: '38', name: '38', checked: false },
  { id: '40', name: '40', checked: false },
  { id: '42', name: '42', checked: false },
  { id: '44', name: '44', checked: false },
  { id: '46', name: '46', checked: false },
  { id: '48', name: '48', checked: false },
  { id: '50', name: '50', checked: false },
  { id: '52', name: '52', checked: false },
  { id: '54', name: '54', checked: false },
  { id: '56', name: '56', checked: false },
  { id: 'EEG', name: 'EEG', checked: false },
  { id: 'EG', name: 'EG', checked: false },
  { id: 'EGG', name: 'EGG', checked: false },
  { id: 'EM', name: 'EM', checked: false },
  { id: 'EP', name: 'EP', checked: false },
  { id: 'epp', name: 'epp', checked: false },
  { id: 'exgg', name: 'exgg', checked: false },
  { id: 'G+', name: 'G+', checked: false },
  { id: 'G/GG', name: 'G/GG', checked: false },
  { id: 'G1', name: 'G1', checked: false },
  { id: 'G2', name: 'G2', checked: false },
  { id: 'G3', name: 'G3', checked: false },
  { id: 'G4', name: 'G4', checked: false },
  { id: 'G5', name: 'G5', checked: false },
  { id: 'GGG', name: 'GGG', checked: false },
  { id: 'L', name: 'L', checked: false },
  { id: 'L/XL', name: 'L/XL', checked: false },
  { id: 'P/M', name: 'P/M', checked: false },
  { id: 'pi', name: 'pi', checked: false },
  { id: 'U', name: 'U', checked: false },
  { id: 'UN', name: 'UN', checked: false },
  { id: 'unic', name: 'unic', checked: false },
  { id: 'XGG', name: 'XGG', checked: false },
  { id: 'Único', name: 'Único', checked: false },
];

export default sizes;
