const articletype = [
  { value: 'Acetinado', label: 'Acetinado' },
  { value: 'Aerado', label: 'Aerado' },
  { value: 'Algodão', label: 'Algodão' },
  { value: 'Amassada(o)', label: 'Amassada(o)' },
  { value: 'Aveludado', label: 'Aveludado' },
  { value: 'Barrado', label: 'Barrado' },
  { value: 'Bordado (a)', label: 'Bordado (a)' },
  { value: 'Bottonê', label: 'Bottonê' },
  { value: 'Brim', label: 'Brim' },
  { value: 'Brocado', label: 'Brocado' },
  { value: 'Cambraia', label: 'Cambraia' },
  { value: 'Camuflado', label: 'Camuflado' },
  { value: 'Canelada (o)', label: 'Canelada (o)' },
  { value: 'Cardada', label: 'Cardada' },
  { value: 'Cetim', label: 'Cetim' },
  { value: 'Chamoix', label: 'Chamoix' },
  { value: 'Chiffon', label: 'Chiffon' },
  { value: 'Cotele', label: 'Cotele' },
  { value: 'Cotton', label: 'Cotton' },
  { value: 'Couro', label: 'Couro' },
  { value: 'Cristal', label: 'Cristal' },
  { value: 'Cru', label: 'Cru' },
  { value: 'Devorê', label: 'Devorê' },
  { value: 'Diversos', label: 'Diversos' },
  { value: 'Escolar', label: 'Escolar' },
  { value: 'Especial', label: 'Especial' },
  { value: 'Estampado (a)', label: 'Estampado (a)' },
  { value: 'Felpa', label: 'Felpa' },
  { value: 'Feltro', label: 'Feltro' },
  { value: 'Fiado', label: 'Fiado' },
  { value: 'Filó', label: 'Filó' },
  { value: 'Fitado', label: 'Fitado' },
  { value: 'Flamê', label: 'Flamê' },
  { value: 'Flanela', label: 'Flanela' },
  { value: 'Floral', label: 'Floral' },
  { value: 'Forro', label: 'Forro' },
  { value: 'Gabardine', label: 'Gabardine' },
  { value: 'Glitter', label: 'Glitter' },
  { value: 'Importado', label: 'Importado' },
  { value: 'Inverno', label: 'Inverno' },
  { value: 'Jeans', label: 'Jeans' },
  { value: 'Jersey', label: 'Jersey' },
  { value: 'Juta', label: 'Juta' },
  { value: 'Lã', label: 'Lã' },
  { value: 'Laminada', label: 'Laminada' },
  { value: 'Linho', label: 'Linho' },
  { value: 'Liso (a)', label: 'Liso (a)' },
  { value: 'Lourex', label: 'Lourex' },
  { value: 'Lycra', label: 'Lycra' },
  { value: 'Mescla', label: 'Mescla' },
  { value: 'Metalico(a)', label: 'Metalico(a)' },
  { value: 'Metalizada(o)', label: 'Metalizada(o)' },
  { value: 'Microfibra', label: 'Microfibra' },
  { value: 'Microtule', label: 'Microtule' },
  { value: 'Mista(o)', label: 'Mista(o)' },
  { value: 'Moletinho', label: 'Moletinho' },
  { value: 'Molhado', label: 'Molhado' },
  { value: 'Neoprene', label: 'Neoprene' },
  { value: 'Nylon', label: 'Nylon' },
  { value: 'Paête', label: 'Paête' },
  { value: 'Pelúcia', label: 'Pelúcia' },
  { value: 'Piquet', label: 'Piquet' },
  { value: 'Plissado', label: 'Plissado' },
  { value: 'Plush', label: 'Plush' },
  { value: 'Poá', label: 'Poá' },
  { value: 'Poliamida', label: 'Poliamida' },
  { value: 'Quadriculado', label: 'Quadriculado' },
  { value: 'Renda', label: 'Renda' },
  { value: 'Ribana', label: 'Ribana' },
  { value: 'Risca de Giz', label: 'Risca de Giz' },
  { value: 'Sarjada', label: 'Sarjada' },
  { value: 'Sirre', label: 'Sirre' },
  { value: 'Strech', label: 'Strech' },
  { value: 'Tinto', label: 'Tinto' },
  { value: 'Tubular', label: 'Tubular' },
  { value: 'Verão', label: 'Verão' },
  { value: 'Vestuário', label: 'Vestuário' },
  { value: 'Viscofaille', label: 'Viscofaille' },
  { value: 'Viscolycra', label: 'Viscolycra' },
  { value: 'Viscose', label: 'Viscose' },
  { value: 'Xadrez', label: 'Xadrez' },
  { value: 'Diversos', label: 'Diversos' },
  { value: 'Outros', label: 'Outros' },
];

export default articletype;
