const composition = [
  { value: '100% Acetato', label: '100% Acetato' },
  { value: '100% Algodão', label: '100% Algodão' },
  { value: '100% Couro', label: '100% Couro' },
  { value: '100% Juta', label: '100% Juta' },
  { value: '100% Lã', label: '100% Lã' },
  { value: '100% nylon', label: '100% nylon' },
  { value: '100% Poliamida', label: '100% Poliamida' },
  { value: '100% Poliéster', label: '100% Poliéster' },
  { value: '100% Polipropileno', label: '100% Polipropileno' },
  { value: '100% Seda', label: '100% Seda' },
  { value: '100% sintetico', label: '100% sintetico' },
  { value: '100% Viscose', label: '100% Viscose' },
  { value: '23% poliéster, 51% viscose, 26% algodão.', label: '23% poliéster, 51% viscose, 26% algodão.' },
  { value: '34% Poliamida/40% Algodão/26% Acetato', label: '34% Poliamida/40% Algodão/26% Acetato' },
  { value: '35% Algodão, 65% Poliéster', label: '35% Algodão, 65% Poliéster' },
  { value: '40% Poliéster 30% Acrílico 30% Poliamida', label: '40% Poliéster 30% Acrílico 30% Poliamida' },
  { value: '48% Poliéster 52% Viscose', label: '48% Poliéster 52% Viscose' },
  { value: '50% acetato 48% poliéster 2% metal', label: '50% acetato 48% poliéster 2% metal' },
  { value: '50% Algodão 50% Poliéster', label: '50% Algodão 50% Poliéster' },
  { value: '50% Algodão/17% Poliéster/13% Viscose/20% Linho', label: '50% Algodão/17% Poliéster/13% Viscose/20% Linho' },
  { value: '50% Juta/50% Algodão', label: '50% Juta/50% Algodão' },
  { value: '50% lã e 50% poliéster', label: '50% lã e 50% poliéster' },
  { value: '50% Poliester 46% Algodão 4% Elastano', label: '50% Poliester 46% Algodão 4% Elastano' },
  { value: '51% Algodão/49% Viscose', label: '51% Algodão/49% Viscose' },
  { value: '52% Poliéster/48% Poliamida', label: '52% Poliéster/48% Poliamida' },
  { value: '52% Viscose/42% Acetato', label: '52% Viscose/42% Acetato' },
  { value: '55% Poliamida/44% Poliéster', label: '55% Poliamida/44% Poliéster' },
  { value: '55% Poliéster/40% Acetato/5% Elastano', label: '55% Poliéster/40% Acetato/5% Elastano' },
  { value: '56% Acetato/44% Poliéster', label: '56% Acetato/44% Poliéster' },
  { value: '56% Poliéster/32% Poliuretano/12% Polipropileno', label: '56% Poliéster/32% Poliuretano/12% Polipropileno' },
  { value: '56% Viscose/44% Poliéster', label: '56% Viscose/44% Poliéster' },
  { value: '57% Poliéster/40% Viscose/3% Metal', label: '57% Poliéster/40% Viscose/3% Metal' },
  { value: '60% Algodão/40% Poliéster', label: '60% Algodão/40% Poliéster' },
  { value: '60% Poliamida/40% Metal', label: '60% Poliamida/40% Metal' },
  { value: '60% Poliéster/40% Poliamida', label: '60% Poliéster/40% Poliamida' },
  { value: '60% Viscose/ 40% Poliéster', label: '60% Viscose/ 40% Poliéster' },
  { value: '62% Poliéster/34% Viscose/4% Elastano', label: '62% Poliéster/34% Viscose/4% Elastano' },
  { value: '63% Juta/36% Algodão/1% Poliéster', label: '63% Juta/36% Algodão/1% Poliéster' },
  { value: '63%acetato 33%Poliamida', label: '63%acetato 33%Poliamida' },
  { value: '65% Algodão/35% Poliéster', label: '65% Algodão/35% Poliéster' },
  { value: '65% poliéster e 35% viscose', label: '65% poliéster e 35% viscose' },
  { value: '65% Poliéster/25% Viscose/10% Metal', label: '65% Poliéster/25% Viscose/10% Metal' },
  { value: '65% Poliéster/32% Algodão/3% Elastano', label: '65% Poliéster/32% Algodão/3% Elastano' },
  { value: '65% Poliéster/35% Algodão', label: '65% Poliéster/35% Algodão' },
  { value: '67% Algodão/30% Poliéster/3% Elastano', label: '67% Algodão/30% Poliéster/3% Elastano' },
  { value: '70% Algodão/30% Poliéster', label: '70% Algodão/30% Poliéster' },
  { value: '70% Poliamida/30% Viscose', label: '70% Poliamida/30% Viscose' },
  { value: '70% Polipropileno/30% Poliéster', label: '70% Polipropileno/30% Poliéster' },
  { value: '70% Viscose/30% Poliéster', label: '70% Viscose/30% Poliéster' },
  { value: '75% Poliéster/25% Algodão', label: '75% Poliéster/25% Algodão' },
  { value: '75% Poliéster/25% Viscose', label: '75% Poliéster/25% Viscose' },
  { value: '77% Algodão/23% Poliéster', label: '77% Algodão/23% Poliéster' },
  { value: '77% Poliéster/23% Metal', label: '77% Poliéster/23% Metal' },
  { value: '80% Acetato/20% Metal', label: '80% Acetato/20% Metal' },
  { value: '80% Metal 20% Poliamida', label: '80% Metal 20% Poliamida' },
  { value: '80% Poliéster/20% Algodão', label: '80% Poliéster/20% Algodão' },
  { value: '80% Poliéster/20% Viscose', label: '80% Poliéster/20% Viscose' },
  { value: '80% Viscose/20% Poliamida', label: '80% Viscose/20% Poliamida' },
  { value: '81% Poliéster/19% Poliamida', label: '81% Poliéster/19% Poliamida' },
  { value: '82% Poliamida/18% Elastano', label: '82% Poliamida/18% Elastano' },
  { value: '84% Poliamida/16% Metal', label: '84% Poliamida/16% Metal' },
  { value: '84% poliéster e 16% Spandex', label: '84% poliéster e 16% Spandex' },
  { value: '85% Algodão 12% Poliester 3% Elastano', label: '85% Algodão 12% Poliester 3% Elastano' },
  { value: '86% Poliéster/14% Viscose', label: '86% Poliéster/14% Viscose' },
  { value: '90% Poliamida/10% Elastano', label: '90% Poliamida/10% Elastano' },
  { value: '90% Poliéster/10% Algodão', label: '90% Poliéster/10% Algodão' },
  { value: '90% Poliéster/10% Metal Pvc', label: '90% Poliéster/10% Metal Pvc' },
  { value: '90% Poliéster/7% Acrilico/3% Fio Metal', label: '90% Poliéster/7% Acrilico/3% Fio Metal' },
  { value: '91% Poliéster/9 % Linho', label: '91% Poliéster/9 % Linho' },
  { value: '92% Algodão/8% Elastano', label: '92% Algodão/8% Elastano' },
  { value: '92% Poliéster/8% Elastano', label: '92% Poliéster/8% Elastano' },
  { value: '95% Algodão/5% Poliéster', label: '95% Algodão/5% Poliéster' },
  { value: '95% Poliamida/5% Metal', label: '95% Poliamida/5% Metal' },
  { value: '95% Poliéster/5% Elastano', label: '95% Poliéster/5% Elastano' },
  { value: '97% Algodão/3% Elastano', label: '97% Algodão/3% Elastano' },
  { value: '97% Poliéster/3% Metal', label: '97% Poliéster/3% Metal' },
  { value: '97% Poliéster/3% Viscose', label: '97% Poliéster/3% Viscose' },
  { value: '98% Poliéster 2% Elastano', label: '98% Poliéster 2% Elastano' },
  { value: '98% Poliéster/2% Metal', label: '98% Poliéster/2% Metal' },
  { value: '99% Algodão 1% Elastano', label: '99% Algodão 1% Elastano' },
  { value: '96% viscose 4% Elastano', label: '96% viscose 4% Elastano' },
  { value: 'Diversos(as)', label: 'Diversos(as)' },
  { value: 'Diversos', label: 'Diversos' },
  { value: 'Outros', label: 'Outros' },
];

export default composition;
