const categoriasFeminino = [
  {
    value: 'Blusas',
    label: 'Blusas',
    subcategorias: [
      { value: 'Diversos', label: 'Diversos' },
      { value: 'Blusas Básicas', label: 'Blusas Básicas' },
      { value: 'Blusas Cropped', label: 'Blusas Cropped' },
      { value: 'Blusa Ciganinha', label: 'Blusa Ciganinha' },
      { value: 'Regata', label: 'Regata' },
      { value: 'Blusa Manga Curta', label: 'Blusa Manga Curta' },
      { value: 'Blusa Manga Longa', label: 'Blusa Manga Longa' },
      { value: 'Camisetas', label: 'Camisetas' },
      { value: 'Pólo', label: 'Pólo' },
      { value: 'Body', label: 'Body' },
      { value: 'Batas e túnicas', label: 'Batas e túnicas' },
    ],
  },
  {
    value: 'Camisas',
    label: 'Camisas',
    subcategorias: [
      { value: 'Diversos', label: 'Diversos' },
      { value: 'Camisa Lisa', label: 'Camisa Lisa' },
      { value: 'Camisas Estampadas', label: 'Camisas Estampadas' },
      { value: 'Camisa Manga Curta', label: 'Camisa Manga Curta' },
      { value: 'Camisa Manga Longa', label: 'Camisa Manga Longa' },
      { value: 'Camisa Sem Manga', label: 'Camisa Sem Manga' },
      { value: 'Camisa Sem Manga', label: 'Camisa Sem Manga' },
    ],
  },

  {
    value: 'Moletom',
    label: 'Moletom',
    subcategorias: [
      { value: 'Diversos', label: 'Diversos' },
      { value: 'Moletom', label: 'Moletom' },
      { value: 'Moletom Aberto', label: 'Moletom Aberto' },
      { value: 'Moletom Fechado', label: 'Moletom Fechado' },
      { value: 'Calça Moletom', label: 'Calça Moletom' },
    ],
  },

  {
    value: 'Casacos e Jaquetas',
    label: 'Casacos e Jaquetas',
    subcategorias: [
      { value: 'Diversos', label: 'Diversos' },
      { value: 'Casacos', label: 'Casacos' },
      { value: 'Jaquetas', label: 'Jaquetas' },
      { value: 'Blazer', label: 'Blazer' },
      { value: 'Colete', label: 'Colete' },
      { value: 'Casaqueto', label: 'Casaqueto' },
      { value: 'Trench Coat', label: 'Trench Coat' },
      { value: 'Parkas', label: 'Parkas' },
    ],
  },
  {
    value: 'Saias',
    label: 'Saias',
    subcategorias: [
      { value: 'Diversos', label: 'Diversos' },
      { value: 'Saia Godê e Evasê', label: 'Saia Godê e Evasê' },
      { value: 'Saia Curta', label: 'Saia Curta' },
      { value: 'Saia Longa', label: 'Saia Longa' },
      { value: 'Minissaia', label: 'Minissaia' },
      { value: 'Saia Jeans', label: 'Saia Jeans' },
      { value: 'Saia Lápis', label: 'Saia Lápis' },
      { value: 'Saia Couro', label: 'Saia Couro' },
      { value: 'Saia Midi', label: 'Saia Midi' },
      { value: 'Saia Suede', label: 'Saia Suede' },
    ],
  },
  {
    value: 'Shorts e Bermudas',
    label: 'Shorts e Bermudas',
    subcategorias: [
      { value: 'Diversos', label: 'Diversos' },
      { value: 'Shorts Jeans', label: 'Shorts Jeans' },
      { value: 'Shorts Tecido', label: 'Shorts Tecido' },
      { value: 'Bermudas', label: 'Bermudas' },
      { value: 'Shorts-Saia', label: 'Shorts-Saia' },
      { value: 'Shorts Sarja', label: 'Shorts Sarja' },
    ],
  },
  {
    value: 'Calças',
    label: 'Calças',
    subcategorias: [
      { value: 'Diversos', label: 'Diversos' },
      { value: 'Calça Sarja', label: 'Calça Sarja' },
      { value: 'Calça Social', label: 'Calça Social' },
      { value: 'Calça Legging', label: 'Calça Legging' },
      { value: 'Calça Jogger', label: 'Calça Jogger' },
      { value: 'Calça Couro', label: 'Calça Couro' },
      { value: 'Calça Cintura Alta', label: 'Calça Cintura Alta' },
      { value: 'Calça Tecido', label: 'Calça Tecido' },
    ],
  },
  {
    value: 'Calças Jeans',
    label: 'Calças Jeans',
    subcategorias: [
      { value: 'Diversos', label: 'Diversos' },
      { value: 'Calça Bootcut', label: 'Calça Bootcut' },
      { value: 'Calça Boyfriend', label: 'Calça Boyfriend' },
      { value: 'Calça Flare', label: 'Calça Flare' },
      { value: 'Calça Jegging', label: 'Calça Jegging' },
      { value: 'Calça Reta', label: 'Calça Reta' },
      { value: 'Calça Skinny', label: 'Calça Skinny' },
    ],
  },
  {
    value: 'Macaquinhos e Macacões',
    label: 'Macaquinhos e Macacões',
    subcategorias: [
      { value: 'Diversos', label: 'Diversos' },
      { value: 'Macaquinho', label: 'Macaquinho' },
      { value: 'Macacão', label: 'Macacão' },
    ],
  },
  {
    value: 'Plus Size',
    label: 'Plus Size',
    subcategorias: [
      { value: 'Diversos', label: 'Diversos' },
      { value: 'Casacos e Jaquetas Plus Size', label: 'Casacos e Jaquetas Plus Size' },
      { value: 'Bermudas e Shorts Plus Size', label: 'Bermudas e Shorts Plus Size' },
      { value: 'Saia Plus Size', label: 'Saia Plus Size' },
      { value: 'Calça Plus Size', label: 'Calça Plus Size' },
      { value: 'Blusas Plus Size', label: 'Blusas Plus Size' },
      { value: 'Vestidos Plus Size', label: 'Vestidos Plus Size' },
      { value: 'Roupas Plus Size', label: 'Roupas Plus Size' },
      { value: 'Lingerie Plus Size', label: 'Lingerie Plus Size' },
    ],
  },
  {
    value: 'Lingerie',
    label: 'Lingerie',
    subcategorias: [
      { value: 'Diversos', label: 'Diversos' },
      { value: 'Lingerie de Algodão', label: 'Lingerie de Algodão' },
      { value: 'Combinação e anáguas', label: 'Combinação e anáguas' },
      { value: 'Sutiãs Esportivos', label: 'Sutiãs Esportivos' },
      { value: 'Necessaires', label: 'Necessaires' },
      { value: 'Sutiãs', label: 'Sutiãs' },
      { value: 'Calcinha', label: 'Calcinha' },
      { value: 'Kit Calcinha e Kit Sutiã', label: 'Kit Calcinha e Kit Sutiã' },
      { value: 'Lingerie de Noiva', label: 'Lingerie de Noiva' },
      { value: 'Lingerie Gestante', label: 'Lingerie Gestante' },
      { value: 'Lingerie Sexy', label: 'Lingerie Sexy' },
      { value: 'Lingerie Básica', label: 'Lingerie Básica' },
      { value: 'Modeladores e Cintas', label: 'Modeladores e Cintas' },
      { value: 'Conjunto e Corselet', label: 'Conjunto e Corselet' },
    ],
  },
  {
    value: 'Pijamas e Camisolas',
    label: 'Pijamas e Camisolas',
    subcategorias: [
      { value: 'Diversos', label: 'Diversos' },
      { value: 'Camisola', label: 'Camisola' },
      { value: 'Camisete e Outerwear', label: 'Camisete e Outerwear' },
      { value: 'Baby Doll e Short Doll', label: 'Baby Doll e Short Doll' },
      { value: 'Pijamas', label: 'Pijamas' },
      { value: 'Robe', label: 'Robe' },
    ],
  },
  {
    value: 'Meias',
    label: 'Meias',
    subcategorias: [
      { value: 'Diversos', label: 'Diversos' },
      { value: 'Meia Soquete', label: 'Meia Soquete' },
      { value: 'Meia Sapatilha', label: 'Meia Sapatilha' },
      { value: 'Meia Calça', label: 'Meia Calça' },
      { value: 'Meia 7/8', label: 'Meia 7/8' },
      { value: 'Meia 3/4', label: 'Meia 3/4' },
    ],
  },
  {
    value: 'Moda Praia',
    label: 'Moda Praia',
    subcategorias: [
      { value: 'Diversos', label: 'Diversos' },
      { value: 'Biquini', label: 'Biquini' },
      { value: 'Biquínis Avulsos', label: 'Biquínis Avulsos' },
      { value: 'Maiô', label: 'Maiô' },
      { value: 'Saídas', label: 'Saídas' },
      { value: 'Body', label: 'Body' },
    ],
  },
  {
    value: 'Vestidos',
    label: 'Vestidos',
    subcategorias: [
      { value: 'Diversos', label: 'Diversos' },
      { value: 'Vestido Curto', label: 'Vestido Curto' },
      { value: 'Vestido Longo', label: 'Vestido Longo' },
      { value: 'Vestido Liso', label: 'Vestido Liso' },
      { value: 'Vestidos Estampados', label: 'Vestidos Estampados' },
      { value: 'Vestido de Renda', label: 'Vestido de Renda' },
      { value: 'Vestido para Noite', label: 'Vestido para Noite' },
      { value: 'Vestido Ciganinha', label: 'Vestido Ciganinha' },
      { value: 'Vestido para Trabalho', label: 'Vestido para Trabalho' },
      { value: 'Vestido Tomara que Caia', label: 'Vestido Tomara que Caia' },
      { value: 'Vestidos Guipures', label: 'Vestidos Guipures' },
      { value: 'Vestido Peplum', label: 'Vestido Peplum' },
      { value: 'Vestido de Festa', label: 'Vestido de Festa' },
      { value: 'Vestido Mullet', label: 'Vestido Mullet' },
    ],
  },
  {
    value: 'Outros',
    label: 'Outros',
    subcategorias: [
      { value: 'Outros ', label: 'Outros ' },
    ],
  },
];

export default categoriasFeminino;
